language: go
env: GO111MODULE=on
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: "qerLIaypAtGIlekTfojFSVBV3Cl1jiRmkJaTCvduMLF0OwgChwngdLDE1j+8F7gba1IudHkidjb3ky69ifipPfODScoWMEz0IgTSuaVmUHmyiqUYKmZTdQ67OgkSUB7gVTekgVntfApMTKl0m+PgE5aIa+y4ngj3oFJoeCOPQouTStQfM3tEsHKP5M541L6RVchYg/w0nt7gN1QPx6LZecFkkTqBT3nqCHRrdz808mirqhwcGvgnQNw6lsNJTX4ozYcNLn4NvXVdSlCOO2jv1b9aIYB5d+vEiVCx3/AfNch3GqIWaE5kGvtJnkvuT3ADnjfWaWcXpR7mpg1DIu7+Cn30Qfjuj3Zgb/Rn/fChxcHD7epYDJRK56gCZC7cjtqkYnBS+JfYM1JekcpslD/sHDpH79dL3vGFyrSfogSS/hpSZ2SkV7RdkjyRjx4nDbEXyVViLn/lJV5As6IWAhJs3su+hIpBrSwhwz+kCQXNp+g4TfkLMjKXzaXsMot4OZCz/fxyScpxCo5/lYKvK4C3thTi5P1us7UNZyMlL42Drj+IsmZ3KHJCb21k6NFLM8lnvf8NF5wZkK3XAwV3o4SEh9g081RoHiv79XnL1s0Jv5CyGvHOR+hDGqwCJiX6LR8Ml7Dq63ntzlLXPmacKcK9g0hWkjYgVMJeSItX0KoTEms="
  app: pokemontengoqueatraparlos

