language: go
env: GO111MODULE=on
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: Q3Mhvu55FNXhosazmw1Ayim51Tt+Ex+aY7h1r9DlZsHm9hix2NQwcdnuLQ08qHjkH6yUbQrfki0/6i/dCENa8IumX5g0bBjuhduQXbeSkJ6PIqhjiNRkIE5aG7Dw89vhNdsBPbXoZMISBVoYTeXgdFJcAnY4uZZnbJoBionyfEy9w1G0fF7kfK7XJyQtISOSUby60Rkgf+7vwwxmrNF6s9qwjz/fPlUKZ0JGbJgoCGVhRgQwaTmRGjaz+khUasI7yhMBz2FTFgZBBnZ/9t73iWdCl2gRMIGtKYkRB8Nn96Gx4zF0NtuTn3R/DFI0m6+PaYwLTdAEfBDPQ5cIChCW5iICN1u+ZyUKzk7lG6fSRUQRzuYcCNPchPGDs8SvVEfquVsZ1Qj+PDAMQF81qYuG/gBNncCV4IftnqYcD3wpq5wFTzW6gLPnQ4LttCEUlY4PuXyGB3X4QdR2dgt6SY1yDFPcurfX7Xwc7LEdp5LNAJ8Gz4qTgft+tkqw0AIcK3L8N9Sb4RwgQSrcIAOxrsA0G+zfDWHd5OMtzVPvLXOFKDTLpomGk7808CJ85yaJLz9MYIya9NnZpQSkI9VVREj3C+b6t+JOM9ybRarReKQqgyBmV7hvA5EyxGpp/vSb0/ENddjnTlz5Z7UlkIUFFKoH6Ohn8zxF/+ZXiZhCRxeVwDI=
  app: pokemontengoqueatraparlos
